const enumNames = {
  // States
  MENU: "MENU",
  TEST: "TEST",
  SET_STATE: "SET_STATE",
  SET_TAB: "SET_TAB",

  // Tabs
  TESTS: "Tests",
  DICTIONARY: "Dictionary",
  SETTINGS: "Settings",

  // Headers
  WORD_TITLE: "Word",
  TRANSLATION_TITLE: "Translation",
  TYPE_TITLE: "Type",
  RATING_TITLE: "Rating",

  // Types
  NOUN: "noun",
  ADJECTIVE: "adjective",
  VERB: "verb",
  ADVERB: "adverb",
  PREPOSITION: "preposition",
  PRONOUN: "pronoun",
  CONJUNCTION: "conjunction",

  // Action types

  // Dictionary
  UPDATE_DICTIONARY: "UPDATE_DICTIONARY",
  LOADING_DICTIONARY: "LOADING_DICTIONARY",
  SET_CHECKED: "SET_CHECKED",
  CHANGE_PAGE: "CHANGE_PAGE",
  CHANGE_ROWS_PER_PAGE: "CHANGE_ROWS_PER_PAGE",
  SET_CHECKED_ALL: "SET_CHECKED_ALL",
  CHANGE_SORT: "CHANGE_SORT",

  // Form
  CLOSE_FORM: "CLOSE_FORM",
  OPEN_FORM: "OPEN_FORM",
  CHANGE_FORM: "CHANGE_FORM",

  // Tests
  UPDATE_TESTS: "UPDATE_TESTS",
  RUN_TEST: "RUN_TEST",
  CLOSE_TEST: "CLOSE_TEST",
  SET_DECK: "SET_DECK",
  SET_QUESTION: "SET_QUESTION",
  SET_ANSWER: "SET_ANSWER",
  SET_ERROR: "SET_ERROR",
  SET_QUESTION_RESULT: "SET_QUESTION_RESULT",
  SET_RESULT: "SET_RESULT",

  //NN
  UPDATE_NN: 'UPDATE_NN',

  // Decks
  RANDOM_WORDS: "RANDOM_WORDS",
  NN_WORDS: "NN_WORDS"
};

export default enumNames;
